name: routine_ade
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '3.4.4'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  image_picker: ^0.8.7
  image: ^3.0.1
  permission_handler: ^11.3.0

  #추가한 패키지
  flutter_calendar_week: ^3.0.1
  intl: ^0.18.0

  cupertino_icons: ^1.0.6
  json_annotation: ^4.0.1
  shelf_swagger_ui: ^1.0.0+2
  http: ^0.13.3
  http_parser: ^4.0.0
  mime: ^1.0.0
  shared_preferences: ^2.0.8
  table_calendar: ^3.0.0
  fl_chart: ^0.69.0
  kakao_flutter_sdk: ^1.1.0 #카카오로그인
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.4
  uni_links: ^0.5.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/office_cleaning.jpg
    - assets/images/moving.jpg
    - assets/images/deep_cleaning.jpg
    - assets/images/interior.jpg
    - assets/images/appliance_cleaning.jpg
    - assets/images/pet_sitting.jpg
    - assets/images/ex1.png
    - assets/images/ex2.png
    - assets/images/ex3.png


